<LoginScreen>:
    orientation: 'vertical'
    Label:
        text: root.error_message
        color: [1, 0, 0, 1]  # Red color for error messages
    TextInput:
        id: username
        hint_text: 'Username'
    TextInput:
        id: password
        hint_text: 'Password'
        password: True
    Button:
        text: 'Login'
        on_press: root.login(username.text, password.text)

    Button:
        text: 'Back'
        on_press: app.root.current = 'welcome'
